config/routes.rb
PhotoManager::Application.routes.draw do
  resources :galleries
  resources :photos, except: :edit

  root :to => 'photos#display'

  get 'tags', to: 'tags#index'
  get 'tags/:tag_name', to: 'tags#show'

  get 'searches', to: 'searches#search'

  match 'testit.json', to: 'json#testit', via: 'post'
  match 'searches.json', to: 'searches#search', via: 'post'

  mount PostgresqlLoStreamer::Engine => "/photo_image"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name, :photo_ids, :gallery_photos

  has_many :gallery_photos, :dependent => :destroy
  has_many :photos, :through => :gallery_photos
end

app/models/gallery_photo.rb
class GalleryPhoto < ActiveRecord::Base
  attr_accessible :gallery, :photo
  belongs_to :gallery
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  acts_as_taggable

  default_scope order('photos.created_at ASC')

  attr_accessible :title, :image, :tag_list, :galleries, :gallery_photos

  validates :title, length: { in: 2..255 }

  mount_uploader :image, ImageUploader

  has_many :photo_tags
  has_many :tags, through: :photo_tags

  has_many :gallery_photos, :dependent => :destroy
  has_many :galleries, :through => :gallery_photos

end

app/models/photo_tag.rb
class PhotoTag < ActiveRecord::Base

  attr_accessible :photo, :tag

  belongs_to :photo
  belongs_to :tag

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def create
    @gallery = Gallery.new(params[:gallery])

    if @gallery.save
      redirect_to @gallery, notice: 'Gallery was successfully created.'
    end
  end

  def update
    @gallery = Gallery.find(params[:id])

    if @gallery.update_attributes(params[:gallery])
      redirect_to @gallery, notice: 'Gallery was successfully updated.'
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    redirect_to galleries_url
  end

end

app/controllers/json_controller.rb
class JsonController < ApplicationController

  def testit()
     puts "Controller: params = #{params}"
     @answer = params[:photo] + "bar"
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  def display
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @search_term = params[:search]

    @photos = Photo.where("title ILIKE ?", "%#{ @search_term }%")
    @galleries = Gallery.where("name ILIKE ?", "%#{ @search_term }%")

    @photos_with_tag = Photo.tagged_with(@search_term)

    respond_to do |format|
      # format.json { @search_term }
      format.json do
        render :json => {:success => true, :html => ( render_partial() )}
      end
    end

  end

  def render_partial
    rendered_string = render_to_string 'searches/search', :formats => [:html]
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag_name = params[:tag_name]
    @photos = Photo.tagged_with(@tag_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/gallaries/_form.html.erb
<%= form_for @gallary do |f| %>
  <% if @gallary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallary.errors.count, "error") %> prohibited this gallary from being saved:</h2>

      <ul>
      <% @gallary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p id="photo_list">
    <%= f.label :photo_ids, "Photos" %><br/>
    <%= f.collection_select :photo_ids, Photo.order(:title), :id, :title, {}, {multiple:true} %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>

  <br />

<% end %>

app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p id="photo_list">
    <%= f.label :photo_ids, "Photos" %><br/>
    <%= f.collection_select :photo_ids, Photo.order(:title), :id, :title, {}, {multiple:true} %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>

  <br />

<% end %>

app/views/galleries/edit.html.erb
<%= render 'partials/header', page_header_title: 'Edit Gallery' %>

<%= render 'form' %>

app/views/galleries/index.html.erb
<%= render 'partials/header', page_header_title: 'Gallaries' %>

<br/><br/>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td><%= gallery.name %></td>
    <td><%= link_to 'Show', gallery %></td>
    <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<%= render 'partials/header', page_header_title: 'Create New Gallery' %>

<%= render 'form' %>

app/views/galleries/show.html.erb
<%= render 'partials/header', page_header_title: "#{ @gallery.name } gallery" %>

<p id="notice"><%= notice %></p>


<div>
  <h2>Name: <%= @gallery.name %></h2>
</div>

<div id='member_photos'>
  <% @gallery.photos.each do |photo| %>
    <%= render 'partials/gallery_photo', photo: photo %>
  <% end %>
</div>

<div class='nav_bar'>
  <%= link_to 'Edit Gallery', edit_gallery_path(@gallery) %> |
  <%= link_to 'Galleries Index', galleries_path %>
</div>

app/views/json/testit.json.erb
<%=
puts("@answer is #{@answer.inspect}")
raw(@answer.to_json) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_gallery_photo.html.erb
<div class="gallery_photo_container">
  <%= image_tag photo.image, class: 'gallery_photo_image' %>
  <div class="gallery_photo_description"><%= link_to photo.title, photo_path(photo) %></div>
</div>

app/views/partials/_header.html.erb
<div class='page_header'>

  <span class='page_header_title'><%= page_header_title %></span>

  <span class='header_nav_links'>
    <%= link_to 'Photos', root_path %> |
    <%= link_to 'Galleries', galleries_path %> |
    <%= link_to 'Tags', tags_path %>
  </span>

  <span class='search_container'>
    <%= render 'searches/form' %>
  </span>

</div>

app/views/partials/_large_photo.html.erb
<div class='large_photo_container'>

  <div>
    <% if photo.image != "" %>
      <%= image_tag photo.image, class: 'large_photo_image' %>
    <% end %>
  </div>

</div>

app/views/photos/_edit_form.html.erb
<%= form_for @photo do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='photo_edit_form_title'>
    <%= f.label :title %>:
    <%= f.text_field :title %>
  </div>

  <div class='tag_field photo_edit_form_tags'>
    <%= f.label :tags %>
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.file_field :image %>
  </p>

  <div class='tag_field'>
    <p>
      <%= f.label :tags %>
      <%= f.text_field :tag_list %>
    </p>
  </div>

  <br />

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/photos/display.html.erb
<%= render 'partials/header', page_header_title: "Photos" %>

<% @photos.each do |photo| %>

    <%= render "partials/large_photo", photo: photo %>

    <%= link_to 'Show', photo %>
    <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br /><br />
<% end %>
<%= link_to 'New Photo', new_photo_path %>

app/views/photos/edit.html.erb
<%= render 'partials/header', page_header_title: "Edit Photo" %>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Front page', root_path %> |
<%= link_to 'Photos Index', photos_path %>

app/views/photos/index.html.erb
<%= render 'partials/header', page_header_title: "Photos Index" %>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.title %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Front page', root_path %> |
<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= render 'partials/header', page_header_title: "Upload New Photo" %>

<%= render 'form' %>

<%= link_to 'Front page', root_path %> |
<%= link_to 'Photos Index', photos_path %>

app/views/photos/show.html.erb
<%= render 'partials/header', page_header_title: "#{ @photo.title }" %>
<p id="notice"><%= notice %></p>

<%= render "partials/large_photo", photo: @photo %>
<%= render 'edit_form' %>

<div>
  <b>Member of galleries:</b>
  <% @photo.galleries.each do |gallery| %>
    <%= link_to gallery.name, gallery_path(gallery) %>
  <% end %>
</div>

<br />

<br />

app/views/searches/_form.html.erb
Search:
<input type='text' id='search_term_field'>
<input type='button' id='search_button' value='Submit'>

app/views/searches/_search_page_body.html.erb
<%= render 'partials/header', page_header_title: "Search for '#{ @search_term }'" %>

<h2 class='float_clear'>Photos:</h2>
<% @photos.each do |photo| %>
  <%= render 'partials/gallery_photo', photo: photo %>
<% end %>

<br/>

<h2 class='float_clear'>Galleries named <%= "#{ @search_term }" %>:</h2>
<% @galleries.each do |gallery| %>

  <h3><%= gallery.name %></h3>
  <% gallery.photos.each do |photo| %>
    <%= render 'partials/gallery_photo', photo: photo %>
  <% end %>
<% end %>

<h2 class='float_clear'>Photos tagged with <%= "#{ @search_term }" %>: </h2>
<% @photos_with_tag.each do |tagged_photo| %>
  <%= render 'partials/gallery_photo', photo: tagged_photo %>
<% end %>

app/views/searches/search.html.erb
<%= render 'partials/header', page_header_title: "Search for '#{ @search_term }'" %>

<h2 class='float_clear'>Photos:</h2>
<% @photos.each do |photo| %>
  <%= render 'partials/gallery_photo', photo: photo %>
<% end %>

<br/>

<h2 class='float_clear'>Galleries named <%= "#{ @search_term }" %>:</h2>
<% @galleries.each do |gallery| %>

  <h3><%= gallery.name %></h3>
  <% gallery.photos.each do |photo| %>
    <%= render 'partials/gallery_photo', photo: photo %>
  <% end %>
<% end %>

<h2 class='float_clear'>Photos tagged with <%= "#{ @search_term }" %>: </h2>
<% @photos_with_tag.each do |tagged_photo| %>
  <%= render 'partials/gallery_photo', photo: tagged_photo %>
<% end %>

app/views/searches/search.json.erb
<%= raw @photos.to_json %>

app/views/tags/index.html.erb
<%= render 'partials/header', page_header_title: "Tag Index" %>

<% @tags.each do |tag| %>
  <%= link_to tag.name, "/tags/#{ tag.name }" %>
  <br/>
<% end %>

app/views/tags/show.html.erb
<%= render 'partials/header', page_header_title: "Photos Tagged '#{ @tag_name }'" %>

<% @photos.each do |photo| %>
  <%= render 'partials/gallery_photo', photo: photo %>
<% end %>